name: Python Application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install and configure Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specifies the exact version to install
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
